version: '3.7'
services: 
  alert:
    image: fahad56/vms-alert:1.0
    container_name: Alerts
    ports: 
      - 8000:8000
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks: 
      - app-network
    depends_on: 
      - mongo
  
  shinobi:
        image: fahad56/vms:1.0
        container_name: Shinobi
        environment:
          - PLUGIN_KEYS={"Tensorflow":"275f20d5b186421deb377c88bb826"}
          - SSL_ENABLED=false
        ports:
          - 8080:8080
        restart: unless-stopped
        networks:
          - app-network
  
  shinobiplugintensorflow:
        image: fahad56/vms-ai:1.0
        container_name: shinobi-tensorflow
        environment:
          - PLUGIN_KEY=275f20d5b186421deb377c88bb826
          - PLUGIN_HOST=Shinobi
        restart: unless-stopped
        networks: 
          - app-network
        depends_on:
          - alert
  
  trudesk:
    image: fahad56/vms-ticketing:1.0
    restart: always
    ports:
      - "8118:8118"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: media123
    volumes:
      - ./database:/data/db
    networks: 
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: media123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: media123
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge